import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { existsSync, statSync } from 'node:fs';
import { extname, join, normalize, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = resolve(fileURLToPath(new URL('../site', import.meta.url)));
const PORT = Number(process.env.PORT ?? 8080);
const TOKEN = process.env.TOKEN ?? 'mock-token';

const TYPES = {
    '.html': 'text/html; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.svg': 'image/svg+xml',
};

const stageSchemas = [
    {
        type: 'icestom:podium',
        label: 'Podium',
        description: 'Puts everyone on the podium in finishing order.',
        options: [
            { name: 'track', type: 'track', label: 'Track', description: 'Which track holds the podium locations', required: true, default: null, min: null, max: null },
        ],
    },
    {
        type: 'icestom:practice',
        label: 'Practice',
        description: 'Free running on a track. Ends when you tell it to.',
        options: [
            { name: 'track', type: 'track', label: 'Track', description: 'Which track to practice on', required: true, default: null, min: null, max: null },
        ],
    },
    {
        type: 'icestom:race',
        label: 'Race',
        description: 'A gridded race. You start the countdown and wave the chequered flag.',
        options: [
            { name: 'track', type: 'track', label: 'Track', description: 'Which track to race on', required: true, default: null, min: null, max: null },
            { name: 'laps', type: 'number', label: 'Laps', description: 'How many laps to complete', required: false, default: 3, min: 1, max: null },
            { name: 'pits', type: 'number', label: 'Pit stops', description: 'How many pit stops are required', required: false, default: 0, min: 0, max: null },
        ],
    },
];

const tracks = ['67circuit', 'aurora-bay', 'frostbite-loop', 'glacier-run'];

const players = [
    { uuid: '11111111-1111-1111-1111-111111111111', name: 'microwavedram' },
    { uuid: '22222222-2222-2222-2222-222222222222', name: 'Frosty' },
    { uuid: '33333333-3333-3333-3333-333333333333', name: 'Skidmark' },
    { uuid: '44444444-4444-4444-4444-444444444444', name: 'Penguin' },
];

const STATE_MACHINES = {
    'icestom:race': {
        initial: 'GRID',
        transitions: {
            GRID: [{ name: 'StartCountdown', to: 'COUNTDOWN' }],
            COUNTDOWN: [],
            RACE: [{ name: 'FinishRace', to: 'CHEQUERED_FLAG' }],
            CHEQUERED_FLAG: [],
            END: [],
        },
    },
    'icestom:practice': {
        initial: 'PRACTICE',
        transitions: {
            PRACTICE: [{ name: 'EndPractice', to: 'END' }],
            END: [],
        },
    },
    'icestom:podium': { initial: null, transitions: {} },
};

const definitions = new Map();

const events = new Map();

seed();

function seed() {
    const document = {
        name: 'Friday Night Grand Prix',
        stages: [
            { type: 'icestom:practice', name: 'Practice', options: { track: '67circuit' } },
            { type: 'icestom:race', name: 'Race', options: { track: '67circuit', laps: 5, pits: 1 } },
            { type: 'icestom:podium', name: 'Podium', options: { track: '67circuit' } },
        ],
    };

    definitions.set('friday-night.luau', {
        name: 'friday-night.luau',
        document,
        source: writeLuau(document),
    });

    definitions.set('handwritten.luau', {
        name: 'handwritten.luau',
        document: null,
        source: '-- written by hand, the panel cannot edit this one\nreturn { name = "Custom" }, function(_, r) return r end\n',
    });
}

function writeLuau(document) {
    const lines = [
        '-- Generated by the IceStom panel.',
        '-- The marker comment below is how the panel reopens this event in the builder.',
        '-- Editing this file by hand is fine, but saving from the builder overwrites it.',
        `-- @panel ${JSON.stringify(document)}`,
        '',
        'local manifest = {',
        `    name = ${quote(document.name)},`,
        '}',
        '',
        'local function run(event, results)',
    ];

    for (const stage of document.stages) {
        lines.push('    do');
        lines.push(`        local stage = event:makeStage(${quote(stage.type)}, {`);
        lines.push(`            name = ${quote(stage.name)},`);

        for (const [key, value] of Object.entries(stage.options)) {
            lines.push(`            ${key} = ${typeof value === 'string' ? quote(value) : String(value)},`);
        }

        lines.push('        })');
        lines.push('');
        lines.push('        results = stage:begin(results):join()');
        lines.push('    end');
        lines.push('');
    }

    lines.push('    return results', 'end', '', 'return manifest, run', '');

    return lines.join('\n');
}

function quote(value) {
    return JSON.stringify(String(value));
}

function snapshot() {
    const busy = new Set();

    const eventList = [...events.values()].map((event) => ({
        id: event.id,
        name: event.name,
        running: true,
        stages: event.stages.map((stage) => {
            for (const uuid of stage.players) busy.add(uuid);

            return {
                name: stage.name,
                type: stage.type,
                state: stage.state,
                transitions: STATE_MACHINES[stage.type]?.transitions[stage.state] ?? [],
                players: stage.players.map((uuid) => ({
                    uuid,
                    name: players.find((player) => player.uuid === uuid)?.name ?? uuid,
                })),
            };
        }),
    }));

    return {
        events: eventList,
        players: players.map((player) => ({ ...player, inEvent: busy.has(player.uuid) })),
    };
}

function bootstrap() {
    return {
        server: { version: '0.3.0-mock', brand: 'IceStom (Mock)' },
        session: {
            owner: 'microwavedram',
            expiresAt: new Date(Date.now() + 55 * 60 * 1000).toISOString(),
        },
        stages: stageSchemas,
        tracks,
        definitions: [...definitions.values()].map(describe),
    };
}

function describe(entry) {
    return {
        name: entry.name,
        editable: Boolean(entry.document),
        document: entry.document,
        title: entry.document?.name ?? entry.name,
    };
}

const streams = new Set();
let lastFrame = null;

setInterval(() => {
    if (streams.size === 0) {
        lastFrame = null;
        return;
    }

    const frame = JSON.stringify(snapshot());

    if (frame === lastFrame) return;

    lastFrame = frame;

    for (const response of streams) response.write(`event: state\ndata: ${frame}\n\n`);
}, 500);

function json(response, status, body) {
    const payload = JSON.stringify(body);
    response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' });
    response.end(payload);
}

function fail(response, status, error) {
    json(response, status, { error });
}

async function body(request) {
    const chunks = [];
    for await (const chunk of request) chunks.push(chunk);

    const text = Buffer.concat(chunks).toString('utf8');

    return text ? JSON.parse(text) : {};
}

function authorised(request, url) {
    const header = request.headers.authorization;

    if (header?.startsWith('Bearer ')) return header.slice(7) === TOKEN;

    return url.searchParams.get('token') === TOKEN;
}

const server = createServer(async (request, response) => {
    const url = new URL(request.url, `http://${request.headers.host}`);

    if (!url.pathname.startsWith('/api/')) {
        await serveStatic(url.pathname, response);
        return;
    }

    if (!authorised(request, url)) {
        fail(response, 401, 'That panel link has expired. Run /panel in game for a new one.');
        return;
    }

    try {
        await handleApi(request, response, url);
    } catch (error) {
        console.error(error);
        fail(response, 500, String(error.message ?? error));
    }
});

async function handleApi(request, response, url) {
    const segments = url.pathname.slice('/api/'.length).split('/').filter(Boolean).map(decodeURIComponent);
    const method = request.method;

    if (segments[0] === 'bootstrap' && method === 'GET') return json(response, 200, bootstrap());
    if (segments[0] === 'state' && method === 'GET') return json(response, 200, snapshot());

    if (segments[0] === 'stream' && method === 'GET') {
        response.writeHead(200, {
            'Content-Type': 'text/event-stream; charset=utf-8',
            'Cache-Control': 'no-cache, no-transform',
            Connection: 'keep-alive',
        });

        response.write(`event: state\ndata: ${JSON.stringify(snapshot())}\n\n`);
        streams.add(response);

        request.on('close', () => streams.delete(response));
        return undefined;
    }

    if (segments.length === 1 && segments[0] === 'definitions' && method === 'POST') {
        const payload = await body(request);
        const name = normaliseName(payload.name);
        const document = payload.document;

        if (!document?.name?.trim()) return fail(response, 400, "Missing or non-string field 'name'");
        if (!Array.isArray(document.stages) || document.stages.length === 0) {
            return fail(response, 400, 'An event needs at least one stage');
        }

        for (const stage of document.stages) {
            const schema = stageSchemas.find((entry) => entry.type === stage.type);

            if (!schema) return fail(response, 400, `Stage type '${stage.type}' can't be built from the panel`);

            for (const option of schema.options) {
                const value = stage.options?.[option.name];

                if ((value === undefined || value === null || value === '') && option.required) {
                    return fail(response, 400, `Stage '${stage.name}' is missing required option '${option.name}'`);
                }
            }
        }

        const entry = { name, document, source: writeLuau(document) };
        definitions.set(name, entry);

        return json(response, 200, { ...describe(entry), source: entry.source });
    }

    if (segments.length === 2 && segments[0] === 'definitions') {
        const name = normaliseName(segments[1]);
        const entry = definitions.get(name);

        if (!entry) return fail(response, 404, `No event definition called ${name}`);

        if (method === 'GET') return json(response, 200, { ...describe(entry), source: entry.source });

        if (method === 'DELETE') {
            definitions.delete(name);
            response.writeHead(204).end();
            return undefined;
        }
    }

    if (segments.length === 1 && segments[0] === 'events' && method === 'POST') {
        const payload = await body(request);
        const entry = definitions.get(normaliseName(payload.definition));

        if (!entry) return fail(response, 404, `No event definition called ${payload.definition}`);

        const id = crypto.randomUUID();
        const participants = payload.participants ?? [];

        const stages = (entry.document?.stages ?? [{ type: 'icestom:race', name: 'Race' }]).map((stage, index) => ({
            name: stage.name,
            type: stage.type,
            state: STATE_MACHINES[stage.type]?.initial ?? null,
            players: index === 0 ? participants : [],
        }));

        events.set(id, { id, name: entry.document?.name ?? entry.name, stages });

        return json(response, 200, { id });
    }

    if (segments.length === 2 && segments[0] === 'events' && method === 'DELETE') {
        if (!events.delete(segments[1])) return fail(response, 404, 'No running event with that id');

        response.writeHead(204).end();
        return undefined;
    }

    if (segments.length === 3 && segments[0] === 'events' && segments[2] === 'transition' && method === 'POST') {
        const payload = await body(request);
        const event = events.get(segments[1]);

        if (!event) return fail(response, 409, 'No running event with that id');

        const stage = event.stages.find((entry) => entry.name.toLowerCase() === payload.stage.toLowerCase());

        if (!stage) return fail(response, 409, `That event has no stage called ${payload.stage}`);

        const legal = STATE_MACHINES[stage.type]?.transitions[stage.state] ?? [];
        const transition = legal.find((entry) => entry.name === payload.transition);

        if (!transition) return fail(response, 409, `${payload.transition} isn't available from ${stage.state}`);

        stage.state = transition.to;

        if (transition.to === 'COUNTDOWN') setTimeout(() => { stage.state = 'RACE'; }, 3000);

        if (transition.to === 'END' || transition.to === 'CHEQUERED_FLAG') handOver(event, stage);

        response.writeHead(204).end();
        return undefined;
    }

    return fail(response, 404, 'No such endpoint');
}

function handOver(event, stage) {
    const index = event.stages.indexOf(stage);
    const next = event.stages[index + 1];

    if (!next) return;

    setTimeout(() => {
        next.players = stage.players;
        stage.players = [];
    }, 1500);
}

function normaliseName(name) {
    const trimmed = String(name ?? '').trim();

    if (!trimmed) return '';

    return trimmed.endsWith('.lua') || trimmed.endsWith('.luau') ? trimmed : `${trimmed}.luau`;
}

async function serveStatic(pathname, response) {
    const relative = normalize(pathname === '/' ? '/index.html' : pathname).replace(/^([/\\])+/, '');
    const file = join(SITE, relative);

    if (!file.startsWith(SITE) || !existsSync(file) || !statSync(file).isFile()) {
        const index = join(SITE, 'index.html');

        response.writeHead(200, { 'Content-Type': TYPES['.html'], 'Cache-Control': 'no-store' });
        response.end(await readFile(index));
        return;
    }

    response.writeHead(200, {
        'Content-Type': TYPES[extname(file)] ?? 'application/octet-stream',
        'Cache-Control': 'no-store',
    });
    response.end(await readFile(file));
}

server.listen(PORT, () => {
    console.log(`Mock IceStom panel on http://localhost:${PORT}`);
    console.log(`Open: http://localhost:${PORT}/#${TOKEN}`);
});
